services:
  fcp-cv-frontend:
    build:
      context: .
    ports:
      - '3000:3000'
    networks:
      - cdp-tenant
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 3s
      timeout: 2s
      retries: 5
    environment:
      USER_AUTH_DISABLED: 'true'
      DAL_TOKEN_GENERATION_DISABLED: 'true'
      DAL_URL: ''
      DAL_EMAIL: ''
      DATAVERSE_URL: ''
      CRM_BASE_URL: ''
      CRM_APP_ID: ''

################################################################################

networks:
  cdp-tenant:
    driver: bridge
    name: cdp-tenant
