services:
  accessibility:
    platform: linux/amd64
    image: defradigital/ffc-axe
    command: >
      axe --dir=/home/node/test-output -s axe.json
        --report=/home/node/test-output --format=junit
        --chrome-options="no-sandbox,disable-setuid-sandbox,disable-dev-shm-usage"
        --chromedriver-path=/usr/bin/chromedriver --exit
        ${CV_URL:-http://fcp-cv-frontend:3000}
    volumes:
      - ./test-output/axe:/home/node/test-output
    networks:
      - network1

networks:
  network1:
    name: cdp-tenant
    external: true
