#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"
# Guarantee clean environment
docker-compose -f docker-compose.yaml -f docker-compose.accessibility.yaml -p fcp-cv-frontend-accessibility-test down -v
# Run AXE test
docker-compose -f docker-compose.yaml -f docker-compose.override.yaml -f docker-compose.accessibility.yaml run --rm accessibility