#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"
# Guarantee clean environment
docker compose -f compose.yml -f compose.accessibility.yaml -p fcp-cv-frontend-accessibility-test down -v --remove-orphans
# Run AXE test
docker compose -f compose.yml -f compose.accessibility.yaml -p fcp-cv-frontend-accessibility-test run --quiet-pull --pull always --build --rm accessibility