name: Check Pull Request

on:
  schedule:
    - cron: '0 7 * * 1'
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup node and install
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: |
          npm audit --omit=dev
          npm ci

      - name: Verify semantic version bump
        run: |
          TARGET_BRANCH_VERSION=$(git show origin/${{ github.base_ref }}:package.json | jq -r '.version')
          PR_BRANCH_VERSION=$(jq -r '.version' package.json)

          if ! npx -y semver -r ">${TARGET_BRANCH_VERSION}" "${PR_BRANCH_VERSION}" > /dev/null  ; then
            echo "ERROR: Branch package.json version (${PR_BRANCH_VERSION}) must be semantically greater than target branch (${TARGET_BRANCH_VERSION})"
            exit 1
          fi

      - name: Test code and Create Test Coverage Reports
        run: |
          npm run lint
          npm test

      - name: Upload Unit Test Coverage Report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: unit-test-coverage-report
          path: coverage/
          retention-days: 7

      - name: Docker build & test accessibility
        run: |
          npm run test:accessibility:docker

      - name: Upload accessibility test report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: accessibility-test-report
          path: test-output/axe/
          retention-days: 7

      # - name: SonarCloud Scan
      #   if: github.actor != 'dependabot[bot]'
      #   uses: SonarSource/sonarqube-scan-action@v7
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
