name: Check Pull Request

on:
  schedule:
    - cron: '0 7 * * 1'
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Test code and Create Test Coverage Reports
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: |
          npm ci
          npm run lint
          set +e
          npm test 2> >( tee test.out >&2 )
          [ `grep '^ERROR: Coverage for' -c test.out ` -eq 9 ] || \
            ( echo 'FAILED: Test or coverage issue' && exit 1 )
      # The above ☝️ checks the test output for any test coverage failures
      # (i.e. lines that start with "ERROR: Coverage for") and counts them.
      # If there are more than 9 such lines, it indicates a new problem with
      # test coverage and the script will exit with an error.
      # NOTE: this is only necessary due to a bug in `vitest` that does not
      # fully honour threshold settings in the config file! 🪲

      - name: Upload Unit Test Coverage Report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: unit-test-coverage-report
          path: coverage/
          retention-days: 7

      - name: Test Docker Image Build
        run: |
          docker build --no-cache --tag cdp-node-frontend-template .

      - name: Test accessibility and create accessibility test report
        run: |
          npm run test:accessibility:docker

      - name: Upload accessibility test report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: accessibility-test-report
          path: test-output/axe/
          retention-days: 7

      # - name: SonarCloud Scan
      #   if: github.actor != 'dependabot[bot]'
      #   uses: SonarSource/sonarqube-scan-action@v7
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
